version: "3.1" 
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_mariadb_sequelize:/var/lib/mysql
      - ./mariadb/initial_data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=renato
      - MYSQL_PASSWORD=123.456
      - MYSQL_ROOT_PASSWORD=123.456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 3307:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_mariadb_sequelize: